dependencies:
  color_tft:
    path: ..
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.1.0
