dependencies:
  color_tft:
    path: ..
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.1.0
